### ISSUE TITLE
Better way to synchronize the scroll of editor panel and preview panel

### ISSUE THREAD

**Issue by moacirrf** [moacirrf/netbeans-markdown#11]

**Comment by Chris2011** [comment]
Hey, I found some little things and I dunno maybe this ticket here is one of my cases so I won't create a new one. So for this, can you please add more info to that, what you mean by that?

**Comment by moacirrf** [comment]
Hi

The problem is how to synchronize the both viewports?, find a way to keep the visible part in same position.
![image](https://user-images.githubusercontent.com/950706/193132838-ce520b7f-afa6-4163-8610-ad850bd950dd.png)
The above image works fine, because is the first line of file or when you are working with small md files.
But look the next image:
![image](https://user-images.githubusercontent.com/950706/193133432-a935c449-36ba-4159-9ec5-eee7ae5a1c44.png)
What will happen if you scroll the left panel to red position? Little messy:
![image](https://user-images.githubusercontent.com/950706/193133735-c02ce37b-9266-4260-97a8-a5c910668e92.png)
The desired result is:
![image](https://user-images.githubusercontent.com/950706/193133891-217fd18d-3b73-492e-b102-2fbb24f53995.png)

Clearly the synchronization must be based on content of the left JEditorPane and not just based on the viewport position.

Until now i cant fix this problem. I tried many ways, but a good way was:
Get the text showing on left panel using [viewToModel2D](https://onlinehelp.unitedplanet.com/apidocs/jdk16/api/java.desktop/javax/swing/plaf/TextUI.html#viewToModel2D(javax.swing.text.JTextComponent,java.awt.geom.Point2D,javax.swing.text.Position.Bias%5B%5D))
So i just search the text on right panel, and scroll to the position using [modelToView](https://onlinehelp.unitedplanet.com/apidocs/jdk16/api/java.desktop/javax/swing/plaf/TextUI.html#modelToView2D(javax.swing.text.JTextComponent,int,javax.swing.text.Position.Bias)) and [scrollRectToVisible](https://docs.oracle.com/javase/7/docs/api/javax/swing/JComponent.html#scrollRectToVisible(java.awt.Rectangle))

Works "well" but the result is not good enough, so i don't publish.

The file that i'm using to test
[teste.md](https://github.com/moacirrf/netbeans-markdown/files/9678882/teste.md)

Thanks

**Comment by Chris2011** [comment]
Ahh now I see it better. Thx :). I always compare the stuff with other editors or IDEs. I can see a difference when I open a large file which is scrollable, in NetBeans with your plugin and use split view or using VS Code. I can say that the scrollbar of the source pane is smaller than the scrollbar of the preview. If that makes sense somehow.
