### ISSUE TITLE
Possible to make the plugin restartless?

### ISSUE THREAD

**Issue by Chris2011** [moacirrf/netbeans-markdown#14]
I know it is just a pom flag to make the plugin restartless, but I think it was added with an intention. So can you please tell me, why you added this flag explicitly? If not, we can just switch it to \<requiresRestart>false\</requiresRestart>

**Comment by moacirrf** [comment]
No, don't works, i tried initially, i believe that is some kind of conflict with **Markdown Support**, my plan is when this plugin is mature enough migrate all this code to Markdown Support ( if community except of course ) so wouldn't worry about it now.

Thanks
