### ISSUE TITLE
Icons should be downsize or replace by Netbeans icons as current icons streches the editor tool bar gaps

### ISSUE THREAD

**Issue by albilu** [moacirrf/netbeans-markdown#46]
Its better to use Netbeans available icons to better fit with Netbeans UI.

Current icons stretches the editor tool bar weirdly and this is not good.
 
![image](https://github.com/moacirrf/netbeans-markdown/assets/35330562/617fcbed-dc83-4744-adea-745096ef2d95)

Normal gap:
![image](https://github.com/moacirrf/netbeans-markdown/assets/35330562/4ed50390-5948-4b02-aea8-67da328d5c0b)

I recommend to use these instead:
Preview:
![image](https://github.com/moacirrf/netbeans-markdown/assets/35330562/00ea1afc-8c66-4b89-a30c-21760ffc1b9d)

Source:
![image](https://github.com/moacirrf/netbeans-markdown/assets/35330562/902d245d-6f6d-45b8-a994-774260290a81)

Split
![image](https://github.com/moacirrf/netbeans-markdown/assets/35330562/6765bdb6-87ba-4585-b5ea-c4f3934221bc)

**Comment by moacirrf** [comment]
Hi,
I will replace by this icons and see how it goes.
thanks
