### ISSUE TITLE
Amazing Work! Any plan to publish to Netbeans Plugin Portal ?

### ISSUE THREAD

**Issue by albilu** [moacirrf/netbeans-markdown#47]
Would be nice to have this plugin in the https://plugins.netbeans.apache.org/

**Comment by moacirrf** [comment]
I have plans, but netbeans guys  are working on a official preview, so I'll see how they evolve that, maybe I'll publish just the export function.

**Comment by moacirrf** [comment]
Hello i published the plugin as you suggested, there is two versions, version 1.0 is verified the version 2 not yet verified.
I will send PRs to improve the internal markdown too.
So I'm closing this issue.

thanks
