### ISSUE TITLE
Unreadable preview on Dark Metal LAF

### ISSUE THREAD

**Issue by terax6669** [moacirrf/netbeans-markdown#69]
![image](https://github.com/moacirrf/netbeans-markdown/assets/19204073/9f5a2853-fd5c-4461-9ade-13671594032b)

**Comment by moacirrf** [comment]
It is not my plugin, this looks the internal official preview of Netbeans that is under development.

**Comment by moacirrf** [comment]
![image](https://github.com/moacirrf/netbeans-markdown/assets/950706/9ff8d61d-7ccf-423c-a5a6-af60df558d50)

**Comment by moacirrf** [comment]
I found the bug they released the development the internal preview on Linux.
You must create this issue on netbeans, not here.
