### ISSUE TITLE
Open file from context menu

### ISSUE THREAD

**Issue by DKnoto** [moacirrf/netbeans-markdown#79]
I recently opened the GoogleTest documentation file in the Markdown 2.0 plugin in NB 19 and Markdown 3.1 in NB 22. In both cases, the visualization works correctly:

![Apache-NetBeans-Plugin-Markdown-2024-09-29](https://github.com/user-attachments/assets/94eb356e-2f35-47ab-a0c9-3672a30bfd07)

But the option to load files in the context menu shown in the source as (file.md) and by underscore in the preview area is sorely missing. Ideally, this file would load by simply clicking ;-)

**Comment by moacirrf** [comment]
Good idea, i will try to do that. I think will be "easy".

Thanks

**Comment by moacirrf** [comment]
Hi, publish in https://github.com/moacirrf/netbeans-markdown/releases/download/latest/netbeans-markdown-3.2.nbm

**Comment by DKnoto** [comment]
I tested it in NB 22, it works :-)
