### ISSUE TITLE
Empty preview on images with relative path

### ISSUE THREAD

**Issue by hajdam** [moacirrf/netbeans-markdown#81]
Hi,
I don't see any preview on markdown files with relative image URLs, for example

`[Image](image.png)`

Example MD: https://github.com/exbin/bined/blob/master/README.md

**Comment by moacirrf** [comment]
![image](https://github.com/user-attachments/assets/1f72934d-8411-4862-a0c6-0ab7ce7681e8)

Curious, i couldn't replicate this error.

Can you share more details? 

- Netbeans version
- S.O, if you are running on linux, what kind of package are you using?( flatpak, snap etc..)
- Plugin version

Thanks

**Comment by hajdam** [comment]
Hi, sorry. I noticed more details later, but as you wrote that you don't have time to work on this plugin anymore, I didn't include it.

As you can see in the link I provided in my previous comment, I use URL parameter in my image link:

`![BinEd-Application Screenshot](images/bined_screenshot.png?raw=true)`

If I drop the `?raw=true` part, it works ok.

I have NetBeans 23 installed from ZIP on Fedora 40 Linux / Oracle JDK 17.0.7. NetBeans Markdown plugin 3.1 from netbeans plugin repository. I also have same behavior on NetBeans 23 / Windows 10.

**Comment by moacirrf** [comment]
I will fix this, until the end of week.
thanks.

**Comment by hajdam** [comment]
Hi, thanks for the work.
Just a note, that removing parameters should not be correct solution here - it works in this case only because there was change in GitHub few years ago and parameter is not needed there anymore. In general case there could be image dependent on parameter(s).
I believe correct solution should more like:
- Use image loader which supports URL parameters
- Add proper exception handling to at least show rest of the document when invalid URL or image is used

Best regards
